"""my first migration

Revision ID: f1b1f1650782
Revises: 
Create Date: 2023-06-02 13:47:29.139265

"""
import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision = "f1b1f1650782"
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "network_config",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("connection", sa.Integer(), nullable=True),
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column("description", sa.String(length=255), nullable=True),
        sa.Column("config", sa.JSON(), nullable=True),
        sa.Column("type", sa.String(length=50), nullable=True),
        sa.Column("infra_type", sa.String(length=50), nullable=True),
        sa.Column("port_channel_id", sa.Integer(), nullable=True),
        sa.Column("max_frame_size", sa.Integer(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("network_config")
    # ### end Alembic commands ###
